# Generated by Django 4.0.5 on 2022-06-27 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/StaffProfilePic/')),
                ('staff_no', models.CharField(max_length=40)),
                ('job_title', models.CharField(max_length=20, null=True)),
                ('division', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('ICT', 'ICT'), ('Legal', 'Legal'), ('GRM', 'GRM'), ('Projects', 'Projects'), ('HR', 'HR'), ('HR', 'HR')], default='ICT', max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('grade', models.IntegerField(max_length=50)),
                ('years_in_current_grade', models.IntegerField(max_length=50)),
                ('years_in_current_position', models.IntegerField(choices=[('ICT', 'ICT'), ('Legal', 'Legal'), ('GRM', 'GRM'), ('Projects', 'Projects'), ('HR', 'HR'), ('HR', 'HR')], default='ICT', max_length=50)),
                ('evaluator', models.CharField(max_length=50)),
                ('duration_evaluator_has_supervised_employee', models.CharField(max_length=50)),
                ('assessment_period', models.IntegerField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
