# Generated by Django 4.0.5 on 2022-06-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_in_current_grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_in_current_position',
            field=models.IntegerField(),
        ),
    ]
