# Generated by Django 4.0.5 on 2022-06-27 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_profile_grade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User_profile',
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc', models.CharField(choices=[('Financial', 'Financial'), ('Customer', 'Customer'), ('Internal Processes', 'Internal Processes'), ('Learning & Growth', 'Learning & Growth'), ('Job Description', 'Job Description')], default='Financial', max_length=50)),
                ('total_bsc_weight', models.IntegerField()),
                ('strategic_initiative', models.CharField(max_length=50)),
                ('initiative_weight', models.IntegerField()),
                ('kpi', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
